In [137]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as  sns
import warnings
warnings.filterwarnings("ignore")

In [138]:
df_app=pd.read_csv(r"C:\Users\Roz Rajak\OneDrive\Desktop\Bank Loan Python\application_data.csv")
df_app

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,157871,0,Cash loans,F,N,N,0,180000.0,1206000.0,45936.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49995,157872,0,Cash loans,M,N,N,0,126000.0,1125000.0,47794.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49996,157873,0,Cash loans,M,N,N,1,112500.0,900000.0,26316.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
49997,157874,0,Cash loans,F,N,Y,0,270000.0,820638.0,34897.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
49998,157875,0,Cash loans,F,N,Y,0,117000.0,254700.0,14751.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [139]:
df_app.index

RangeIndex(start=0, stop=49999, step=1)

In [140]:
df_app.shape

(49999, 122)

In [141]:
df_app.size

6099878

In [142]:
#dataframeobject.head([number])-5
df_app.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [143]:
#dataframeobject.tail([number])-5
df_app.tail()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
49994,157871,0,Cash loans,F,N,N,0,180000.0,1206000.0,45936.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49995,157872,0,Cash loans,M,N,N,0,126000.0,1125000.0,47794.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49996,157873,0,Cash loans,M,N,N,1,112500.0,900000.0,26316.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
49997,157874,0,Cash loans,F,N,Y,0,270000.0,820638.0,34897.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
49998,157875,0,Cash loans,F,N,Y,0,117000.0,254700.0,14751.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [144]:
#dataframeobject.sample(n=[1])
df_app.sample(n=5)     #It randomly selects 5 rows from the DataFrame

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
6025,107053,0,Cash loans,F,N,Y,0,112500.0,622188.0,22477.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
47408,154900,0,Revolving loans,M,Y,Y,2,225000.0,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2114,102486,0,Cash loans,F,N,Y,1,112500.0,364846.5,11583.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
1609,101888,0,Cash loans,M,Y,N,0,153000.0,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
26180,130446,0,Cash loans,F,N,Y,0,54000.0,143910.0,14148.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0

In [145]:
#This function gives you a quick summary of the DataFrame.
df_app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(64), int64(42), object(16)
memory usage: 46.5+ MB

In [146]:
#This gives a detailed summary of the DataFrame.
df_app.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 122 columns):
 #    Column                        Non-Null Count  Dtype
---   ------                        --------------  -----
 0    SK_ID_CURR                    49999 non-null  int64
 1    TARGET                        49999 non-null  int64
 2    NAME_CONTRACT_TYPE            49999 non-null  object
 3    CODE_GENDER                   49999 non-null  object
 4    FLAG_OWN_CAR                  49999 non-null  object
 5    FLAG_OWN_REALTY               49999 non-null  object
 6    CNT_CHILDREN                  49999 non-null  int64
 7    AMT_INCOME_TOTAL              49999 non-null  float64
 8    AMT_CREDIT                    49999 non-null  float64
 9    AMT_ANNUITY                   49998 non-null  float64
 10   AMT_GOODS_PRICE               49961 non-null  float64
 11   NAME_TYPE_SUITE               49807 non-null  object
 12   NAME_INCOME_TYPE              49999 non-null  object
 13   NAME_EDUCATION_TYPE           49999 non-null  object
 14   NAME_FAMILY_STATUS            49999 non-null  object
 15   NAME_HOUSING_TYPE             49999 non-null  object
 16   REGION_POPULATION_RELATIVE    49999 non-null  float64
 17   DAYS_BIRTH                    49999 non-null  int64
 18   DAYS_EMPLOYED                 49999 non-null  int64
 19   DAYS_REGISTRATION             49999 non-null  int64
 20   DAYS_ID_PUBLISH               49999 non-null  int64
 21   OWN_CAR_AGE                   17049 non-null  float64
 22   FLAG_MOBIL                    49999 non-null  int64
 23   FLAG_EMP_PHONE                49999 non-null  int64
 24   FLAG_WORK_PHONE               49999 non-null  int64
 25   FLAG_CONT_MOBILE              49999 non-null  int64
 26   FLAG_PHONE                    49999 non-null  int64
 27   FLAG_EMAIL                    49999 non-null  int64
 28   OCCUPATION_TYPE               34345 non-null  object
 29   CNT_FAM_MEMBERS               49998 non-null  float64
 30   REGION_RATING_CLIENT          49999 non-null  int64
 31   REGION_RATING_CLIENT_W_CITY   49999 non-null  int64
 32   WEEKDAY_APPR_PROCESS_START    49999 non-null  object
 33   HOUR_APPR_PROCESS_START       49999 non-null  int64
 34   REG_REGION_NOT_LIVE_REGION    49999 non-null  int64
 35   REG_REGION_NOT_WORK_REGION    49999 non-null  int64
 36   LIVE_REGION_NOT_WORK_REGION   49999 non-null  int64
 37   REG_CITY_NOT_LIVE_CITY        49999 non-null  int64
 38   REG_CITY_NOT_WORK_CITY        49999 non-null  int64
 39   LIVE_CITY_NOT_WORK_CITY       49999 non-null  int64
 40   ORGANIZATION_TYPE             49999 non-null  object
 41   EXT_SOURCE_1                  21827 non-null  float64
 42   EXT_SOURCE_2                  49873 non-null  float64
 43   EXT_SOURCE_3                  40055 non-null  float64
 44   APARTMENTS_AVG                24614 non-null  float64
 45   BASEMENTAREA_AVG              20800 non-null  float64
 46   YEARS_BEGINEXPLUATATION_AVG   25605 non-null  float64
 47   YEARS_BUILD_AVG               16760 non-null  float64
 48   COMMONAREA_AVG                15039 non-null  float64
 49   ELEVATORS_AVG                 23348 non-null  float64
 50   ENTRANCES_AVG                 24804 non-null  float64
 51   FLOORSMAX_AVG                 25124 non-null  float64
 52   FLOORSMIN_AVG                 16105 non-null  float64
 53   LANDAREA_AVG                  20278 non-null  float64
 54   LIVINGAPARTMENTS_AVG          15773 non-null  float64
 55   LIVINGAREA_AVG                24862 non-null  float64
 56   NONLIVINGAPARTMENTS_AVG       15285 non-null  float64
 57   NONLIVINGAREA_AVG             22427 non-null  float64
 58   APARTMENTS_MODE               24614 non-null  float64
 59   BASEMENTAREA_MODE             20800 non-null  float64
 60   YEARS_BEGINEXPLUATATION_MODE  25605 non-null  float64
 61   YEARS_BUILD_MODE              16760 non-null  float64
 62   COMMONAREA_MODE               15039 non-null  float64
 63   ELEVATORS_MODE                23348 non-null  float64
 64   ENTRANCES_MODE                24804 non-null  float64
 65   FLOORSMAX_MODE                25124 non-null  float64
 66   FLOORSMIN_MODE                16105 non-null  float64
 67   LANDAREA_MODE                 20278 non-null  float64
 68   LIVINGAPARTMENTS_MODE         15773 non-null  float64
 69   LIVINGAREA_MODE               24862 non-null  float64
 70   NONLIVINGAPARTMENTS_MODE      15285 non-null  float64
 71   NONLIVINGAREA_MODE            22427 non-null  float64
 72   APARTMENTS_MEDI               24614 non-null  float64
 73   BASEMENTAREA_MEDI             20800 non-null  float64
 74   YEARS_BEGINEXPLUATATION_MEDI  25605 non-null  float64
 75   YEARS_BUILD_MEDI              16760 non-null  float64
 76   COMMONAREA_MEDI               15039 non-null  float64
 77   ELEVATORS_MEDI                23348 non-null  float64
 78   ENTRANCES_MEDI                24804 non-null  float64
 79   FLOORSMAX_MEDI                25124 non-null  float64
 80   FLOORSMIN_MEDI                16105 non-null  float64
 81   LANDAREA_MEDI                 20278 non-null  float64
 82   LIVINGAPARTMENTS_MEDI         15773 non-null  float64
 83   LIVINGAREA_MEDI               24862 non-null  float64
 84   NONLIVINGAPARTMENTS_MEDI      15285 non-null  float64
 85   NONLIVINGAREA_MEDI            22427 non-null  float64
 86   FONDKAPREMONT_MODE            15808 non-null  object
 87   HOUSETYPE_MODE                24924 non-null  object
 88   TOTALAREA_MODE                25851 non-null  float64
 89   WALLSMATERIAL_MODE            24540 non-null  object
 90   EMERGENCYSTATE_MODE           26301 non-null  object
 91   OBS_30_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 92   DEF_30_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 93   OBS_60_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 94   DEF_60_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 95   DAYS_LAST_PHONE_CHANGE        49998 non-null  float64
 96   FLAG_DOCUMENT_2               49999 non-null  int64
 97   FLAG_DOCUMENT_3               49999 non-null  int64
 98   FLAG_DOCUMENT_4               49999 non-null  int64
 99   FLAG_DOCUMENT_5               49999 non-null  int64
 100  FLAG_DOCUMENT_6               49999 non-null  int64
 101  FLAG_DOCUMENT_7               49999 non-null  int64
 102  FLAG_DOCUMENT_8               49999 non-null  int64
 103  FLAG_DOCUMENT_9               49999 non-null  int64
 104  FLAG_DOCUMENT_10              49999 non-null  int64
 105  FLAG_DOCUMENT_11              49999 non-null  int64
 106  FLAG_DOCUMENT_12              49999 non-null  int64
 107  FLAG_DOCUMENT_13              49999 non-null  int64
 108  FLAG_DOCUMENT_14              49999 non-null  int64
 109  FLAG_DOCUMENT_15              49999 non-null  int64
 110  FLAG_DOCUMENT_16              49999 non-null  int64
 111  FLAG_DOCUMENT_17              49999 non-null  int64
 112  FLAG_DOCUMENT_18              49999 non-null  int64
 113  FLAG_DOCUMENT_19              49999 non-null  int64
 114  FLAG_DOCUMENT_20              49999 non-null  int64
 115  FLAG_DOCUMENT_21              49999 non-null  int64
 116  AMT_REQ_CREDIT_BUREAU_HOUR    43265 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_DAY     43265 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_WEEK    43265 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_MON     43265 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_QRT     43265 non-null  float64
 121  AMT_REQ_CREDIT_BUREAU_YEAR    43265 non-null  float64
dtypes: float64(64), int64(42), object(16)
memory usage: 46.5+ MB

In [147]:
#This returns a list of all column names in the DataFrame.
df_app.columns.to_list()

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [148]:
#This shows the data type of every column in the DataFrame.
df_app.dtypes

SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     float64
AMT_REQ_CREDIT_BUREAU_WEEK    float64
AMT_REQ_CREDIT_BUREAU_MON     float64
AMT_REQ_CREDIT_BUREAU_QRT     float64
AMT_REQ_CREDIT_BUREAU_YEAR    float64
Length: 122, dtype: object

In [149]:
#This selects only the CODE_GENDER column from the df_app DataFrame.
df_app["CODE_GENDER"]

0        M
1        F
2        M
3        F
4        M
        ..
49994    F
49995    M
49996    M
49997    F
49998    F
Name: CODE_GENDER, Length: 49999, dtype: object

In [150]:
df_app[["CODE_GENDER","NAME_CONTRACT_TYPE"]]

      CODE_GENDER NAME_CONTRACT_TYPE
0               M         Cash loans
1               F         Cash loans
2               M    Revolving loans
3               F         Cash loans
4               M         Cash loans
...           ...                ...
49994           F         Cash loans
49995           M         Cash loans
49996           M         Cash loans
49997           F         Cash loans
49998           F         Cash loans

[49999 rows x 2 columns]

In [151]:
#This gives a statistical summary of the numerical columns in your DataFrame.
df_app.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,49999.000000,49999.000000,49999.000000,4.999900e+04,4.999900e+04,49998.000000,4.996100e+04,49999.000000,49999.000000,49999.000000,...,49999.000000,49999.000000,49999.000000,49999.00000,43265.000000,43265.000000,43265.000000,43265.000000,43265.000000,43265.000000
mean,129013.210584,0.080522,0.419848,1.707676e+05,5.997006e+05,27107.377355,5.390600e+05,0.020798,-16022.042081,63219.424488,...,0.008500,0.000700,0.000520,0.00038,0.007096,0.007512,0.032382,0.270288,0.260973,1.881035
std,16690.512048,0.272102,0.724039,5.318191e+05,4.024154e+05,14562.944435,3.698533e+05,0.013761,4361.400270,140794.605668,...,0.091805,0.026449,0.022798,0.01949,0.087709,0.107992,0.194080,0.928560,0.606996,1.865054
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,2052.000000,4.500000e+04,0.000533,-25184.000000,-17531.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,114570.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16456.500000,2.385000e+05,0.010006,-19644.000000,-2786.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,129076.000000,0.000000,0.000000,1.458000e+05,5.147775e+05,24939.000000,4.500000e+05,0.018850,-15731.000000,-1221.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,143438.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12378.500000,-292.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,157875.000000,1.000000,11.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7680.000000,365243.000000,...,1.000000,1.000000,1.000000,1.00000,3.000000,6.000000,6.000000,24.000000,8.000000,25.000000

In [152]:
#This gives a statistical summary of categorical/text columns instead of numerical columns
df_app.describe(include=["object"])

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,FONDKAPREMONT_MODE,HOUSETYPE_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE
count,49999,49999,49999,49999,49807,49999,49999,49999,49999,34345,49999,49999,15808,24924,24540,26301
unique,2,3,2,2,7,8,5,6,6,18,7,58,4,3,7,2
top,Cash loans,F,N,Y,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,Laborers,TUESDAY,Business Entity Type 3,reg oper account,block of flats,Panel,No
freq,45276,32823,32949,34691,40435,26010,35572,32094,44368,8952,8741,11101,12045,24453,10648,25944

In [153]:
df_app.describe().columns

Index(['SK_ID_CURR', 'TARGET', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=106)

In [154]:
df_app.describe(include="object").columns

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
       'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='object')

In [155]:
set(df_app.columns)-set(df_app.describe().columns)

{'CODE_GENDER',
 'EMERGENCYSTATE_MODE',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'NAME_CONTRACT_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'NAME_INCOME_TYPE',
 'NAME_TYPE_SUITE',
 'OCCUPATION_TYPE',
 'ORGANIZATION_TYPE',
 'WALLSMATERIAL_MODE',
 'WEEKDAY_APPR_PROCESS_START'}

In [156]:
#dataframeobj.nunique()-return unique value count of each columns
df_app.nunique()

SK_ID_CURR                    49999
TARGET                            2
NAME_CONTRACT_TYPE                2
CODE_GENDER                       3
FLAG_OWN_CAR                      2
                              ...
AMT_REQ_CREDIT_BUREAU_DAY         7
AMT_REQ_CREDIT_BUREAU_WEEK        7
AMT_REQ_CREDIT_BUREAU_MON        20
AMT_REQ_CREDIT_BUREAU_QRT         9
AMT_REQ_CREDIT_BUREAU_YEAR       19
Length: 122, dtype: int64

In [157]:
df_app["CODE_GENDER"].nunique()

3

In [158]:
#dataframeobj[columname].unique() ----- return unique value of particular cloumns
df_app["OCCUPATION_TYPE"].unique()

array(['Laborers', 'Core staff', 'Accountants', 'Managers', nan,
       'Drivers', 'Sales staff', 'Cleaning staff', 'Cooking staff',
       'Private service staff', 'Medicine staff', 'Security staff',
       'High skill tech staff', 'Waiters/barmen staff',
       'Low-skill Laborers', 'Realty agents', 'Secretaries', 'IT staff',
       'HR staff'], dtype=object)

In [159]:
#sort_value(by="columname",ascending=True)
df_app.sort_values(by="TARGET").head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
24999,129076,0,Cash loans,M,N,Y,0,121500.0,518562.0,21969.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
32628,137817,0,Cash loans,F,N,Y,2,72000.0,117000.0,6844.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
32629,137818,0,Cash loans,F,Y,Y,0,135000.0,942300.0,27679.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
32630,137819,0,Cash loans,F,Y,N,1,202500.0,675000.0,34465.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
32631,137820,0,Cash loans,M,Y,Y,0,225000.0,779688.0,31050.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

In [160]:
df_app.sort_values(by="TARGET",ascending=False).head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
29588,134357,1,Cash loans,M,Y,N,0,162000.0,398016.0,31576.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
16863,119664,1,Cash loans,F,Y,Y,0,180000.0,640080.0,31261.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
4567,105339,1,Cash loans,F,N,Y,0,142200.0,1125000.0,37309.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
34457,139926,1,Cash loans,F,N,Y,0,135000.0,1057500.0,30127.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [161]:
df_app.sort_values(by="CODE_GENDER")

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
49998,157875,0,Cash loans,F,N,Y,0,117000.0,254700.0,14751.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
24082,128009,0,Cash loans,F,N,N,0,157500.0,612612.0,29601.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
24081,128008,0,Cash loans,F,N,Y,0,135000.0,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
24080,128007,0,Cash loans,F,N,Y,0,315000.0,621000.0,18288.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
24079,128006,1,Cash loans,F,Y,Y,0,112500.0,382500.0,18531.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24914,128975,0,Cash loans,M,Y,Y,0,135000.0,945000.0,42286.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
24948,129016,0,Cash loans,M,N,Y,3,225000.0,1739470.5,52870.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
24999,129076,0,Cash loans,M,N,Y,0,121500.0,518562.0,21969.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
35657,141289,0,Revolving loans,XNA,Y,Y,0,207000.0,382500.0,19125.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
38566,144669,0,Revolving loans,XNA,N,Y,2,157500.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,3.0,0.0,4.0

In [162]:
df_app["CODE_GENDER"].sort_values(ascending=False)

38566    XNA
35657    XNA
0          M
25362      M
25392      M
        ...
25980      F
8314       F
8315       F
25977      F
49998      F
Name: CODE_GENDER, Length: 49999, dtype: object

In [163]:
df_app["CODE_GENDER"].value_counts()

CODE_GENDER
F      32823
M      17174
XNA        2
Name: count, dtype: int64

In [164]:
df_app["CODE_GENDER"].value_counts().index

Index(['F', 'M', 'XNA'], dtype='object', name='CODE_GENDER')

In [165]:
df_app["CODE_GENDER"].value_counts(normalize=True)

CODE_GENDER
F      0.656473
M      0.343487
XNA    0.000040
Name: proportion, dtype: float64

In [166]:
df_app["CODE_GENDER"].value_counts(normalize=True)*100

CODE_GENDER
F      65.647313
M      34.348687
XNA     0.004000
Name: proportion, dtype: float64

In [167]:
#null values
#pd.isna(dataframe)
pd.isna(df_app).head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [168]:
df_app.isnull()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [169]:
df_app.isnull().sum()

SK_ID_CURR                       0
TARGET                           0
NAME_CONTRACT_TYPE               0
CODE_GENDER                      0
FLAG_OWN_CAR                     0
                              ...
AMT_REQ_CREDIT_BUREAU_DAY     6734
AMT_REQ_CREDIT_BUREAU_WEEK    6734
AMT_REQ_CREDIT_BUREAU_MON     6734
AMT_REQ_CREDIT_BUREAU_QRT     6734
AMT_REQ_CREDIT_BUREAU_YEAR    6734
Length: 122, dtype: int64

In [170]:
df_app["AMT_ANNUITY"].isnull().sum()

np.int64(1)

In [171]:
round(df_app.isnull().sum()/len(df_app)*100,2).sort_values(ascending=False)

COMMONAREA_MEDI             69.92
COMMONAREA_AVG              69.92
COMMONAREA_MODE             69.92
NONLIVINGAPARTMENTS_MODE    69.43
NONLIVINGAPARTMENTS_AVG     69.43
                            ...
NAME_FAMILY_STATUS           0.00
NAME_EDUCATION_TYPE          0.00
NAME_INCOME_TYPE             0.00
AMT_ANNUITY                  0.00
SK_ID_CURR                   0.00
Length: 122, dtype: float64

In [172]:
def missing_values(dataframe):
    return round(dataframe.isnull().sum()/len(dataframe)*100,2).sort_values(ascending=False)

In [173]:
missing_values(df_app)

COMMONAREA_MEDI             69.92
COMMONAREA_AVG              69.92
COMMONAREA_MODE             69.92
NONLIVINGAPARTMENTS_MODE    69.43
NONLIVINGAPARTMENTS_AVG     69.43
                            ...
NAME_FAMILY_STATUS           0.00
NAME_EDUCATION_TYPE          0.00
NAME_INCOME_TYPE             0.00
AMT_ANNUITY                  0.00
SK_ID_CURR                   0.00
Length: 122, dtype: float64

In [174]:
df_prev=pd.read_csv(r"C:\Users\Roz Rajak\OneDrive\Desktop\Bank Loan Python\previous_application.csv")
df_prev

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,1171956,339569,Cash loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,11,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
49995,1904808,363980,Cash loans,NaN,0.0,0.0,NaN,NaN,FRIDAY,10,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
49996,2331005,231295,Cash loans,22176.405,180000.0,216418.5,NaN,180000.0,TUESDAY,12,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-670.0,-340.0,-340.0,-338.0,1.0
49997,1960897,346691,Cash loans,NaN,0.0,0.0,NaN,NaN,WEDNESDAY,16,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
49998,1979352,363244,Cash loans,24909.390,360000.0,409896.0,NaN,360000.0,FRIDAY,18,...,XNA,36.0,high,Cash X-Sell: high,NaN,NaN,NaN,NaN,NaN,NaN

In [175]:
missing_values(df_prev)

RATE_INTEREST_PRIVILEGED       99.67
RATE_INTEREST_PRIMARY          99.67
RATE_DOWN_PAYMENT              50.40
AMT_DOWN_PAYMENT               50.40
NAME_TYPE_SUITE                48.49
NFLAG_INSURED_ON_APPROVAL      38.32
DAYS_FIRST_DRAWING             38.32
DAYS_FIRST_DUE                 38.32
DAYS_LAST_DUE_1ST_VERSION      38.32
DAYS_LAST_DUE                  38.32
DAYS_TERMINATION               38.32
AMT_GOODS_PRICE                21.49
AMT_ANNUITY                    21.18
CNT_PAYMENT                    21.18
PRODUCT_COMBINATION             0.02
CHANNEL_TYPE                    0.00
NAME_PRODUCT_TYPE               0.00
NAME_YIELD_GROUP                0.00
SELLERPLACE_AREA                0.00
NAME_SELLER_INDUSTRY            0.00
NAME_GOODS_CATEGORY             0.00
NAME_PORTFOLIO                  0.00
SK_ID_PREV                      0.00
NAME_CLIENT_TYPE                0.00
CODE_REJECT_REASON              0.00
SK_ID_CURR                      0.00
DAYS_DECISION                   0.00
NAME_CONTRACT_STATUS            0.00
NAME_CASH_LOAN_PURPOSE          0.00
NFLAG_LAST_APPL_IN_DAY          0.00
FLAG_LAST_APPL_PER_CONTRACT     0.00
HOUR_APPR_PROCESS_START         0.00
WEEKDAY_APPR_PROCESS_START      0.00
AMT_CREDIT                      0.00
AMT_APPLICATION                 0.00
NAME_CONTRACT_TYPE              0.00
NAME_PAYMENT_TYPE               0.00
dtype: float64

In [176]:
missing_values(df_app)[missing_values(df_app)>50]

COMMONAREA_MEDI             69.92
COMMONAREA_AVG              69.92
COMMONAREA_MODE             69.92
NONLIVINGAPARTMENTS_MODE    69.43
NONLIVINGAPARTMENTS_AVG     69.43
NONLIVINGAPARTMENTS_MEDI    69.43
LIVINGAPARTMENTS_MODE       68.45
LIVINGAPARTMENTS_AVG        68.45
LIVINGAPARTMENTS_MEDI       68.45
FONDKAPREMONT_MODE          68.38
FLOORSMIN_AVG               67.79
FLOORSMIN_MODE              67.79
FLOORSMIN_MEDI              67.79
YEARS_BUILD_MEDI            66.48
YEARS_BUILD_MODE            66.48
YEARS_BUILD_AVG             66.48
OWN_CAR_AGE                 65.90
LANDAREA_MEDI               59.44
LANDAREA_MODE               59.44
LANDAREA_AVG                59.44
BASEMENTAREA_MEDI           58.40
BASEMENTAREA_AVG            58.40
BASEMENTAREA_MODE           58.40
EXT_SOURCE_1                56.35
NONLIVINGAREA_MODE          55.15
NONLIVINGAREA_AVG           55.15
NONLIVINGAREA_MEDI          55.15
ELEVATORS_MEDI              53.30
ELEVATORS_AVG               53.30
ELEVATORS_MODE              53.30
WALLSMATERIAL_MODE          50.92
APARTMENTS_MEDI             50.77
APARTMENTS_AVG              50.77
APARTMENTS_MODE             50.77
ENTRANCES_MEDI              50.39
ENTRANCES_AVG               50.39
ENTRANCES_MODE              50.39
LIVINGAREA_AVG              50.28
LIVINGAREA_MODE             50.28
LIVINGAREA_MEDI             50.28
HOUSETYPE_MODE              50.15
dtype: float64

In [177]:
null.index

NameError: name 'null' is not defined

In [ ]:
null=missing_values(df_app)[missing_values(df_app)>50]

In [ ]:
df_app.drop(columns=null.index,inplace=True)

In [ ]:
df_app.head()

In [ ]:
null1=missing_values(df_app)[missing_values(df_app)>40]

In [ ]:
null1.index

In [ ]:
df_app.drop(columns=null1.index,inplace=True)

In [ ]:
df_app.head()

In [ ]:
null=missing_values(df_app)[missing_values(df_app)>40]

In [ ]:
null1.index

In [ ]:
df_app.drop(columns=null1.index,inplace=True)

In [ ]:
df_app.head()

In [ ]:
plt.figure(figsize=(10,6))
sns.histplot(df_app["AMT_ANNUITY"],kde=True,color="purple")
plt.title("Distrinution plot of AMT_ANNUITY")
plt.xlabel("AMT_ANNUITY")
plt.ylabel("FRQUENCY")
plt.show()

In [ ]:
mean=df_app["AMT_ANNUITY"].mean()
mean

In [ ]:
median=df_app["AMT_ANNUITY"].mean()
median

In [ ]:
q1=np.quantile(df_app["AMT_ANNUITY"].dropna(),0.25)
q1

In [ ]:
q2=np.quantile(df_app["AMT_ANNUITY"].dropna(),0.50)
q2

In [ ]:
q3=np.quantile(df_app["AMT_ANNUITY"].dropna(),0.75)
q3

In [ ]:
IQR=q3-q1
IQR

In [ ]:
lower_fence=q1-(1.5*IQR)
lower_fence

In [ ]:
UPPER_FENCE=q3+(1.5*IQR)
UPPER_FENCE

In [ ]:
l=[]
for i in df_app["AMT_ANNUITY"]:
    if i > UPPER_FENCE or i<lower_fence:
        l.append(i)
print(len(l))

In [ ]:
df_app["AMT_ANNUITY"]=df_app["AMT_ANNUITY"].fillna(df_app["AMT_ANNUITY"].median())

In [ ]:
df_app["AMT_ANNUITY"].isnull().sum()

In [ ]:
df_app["AMT_GOODS_PRICE"].isnull().sum()

In [ ]:
df_app["AMT_GOODS_PRICE"].describe()

In [ ]:
sns.boxplot(x=df_app["AMT_GOODS_PRICE"],color="green")
plt.show

In [ ]:
plt.figure(figsize=(10,6))
sns.histplot(df_app["AMT_GOODS_PRICE"],kde=True,color="purple")
plt.title(f'AMT_GOODS_PRICE DISTRIBUTION PLOT' )
plt.xlabel("AMT_GOODS_PRICE")
plt.ylabel("FRQUENCY")
plt.show()

In [ ]:
df_app["AMT_CREDIT"].isnull().sum()

In [ ]:
df_app["AMT_GOODS_PRICE"]=df_app["AMT_GOODS_PRICE"].fillna(df_app["AMT_CREDIT"])

In [ ]:
df_app["AMT_GOODS_PRICE"].isnull().sum()

In [ ]:
df_app["OCCUPATION_TYPE"].isnull().sum()

In [ ]:
df_app["OCCUPATION_TYPE"].mode()[0]

In [ ]:
df_app["OCCUPATION_TYPE"]=df_app["OCCUPATION_TYPE"].fillna("Others")

In [ ]:
df_app["OCCUPATION_TYPE"].isnull().sum()

In [ ]:
df_app["OCCUPATION_TYPE"].value_counts()

In [ ]:
df_app["OCCUPATION_TYPE"].value_counts().index

In [ ]:
plt.figure(figsize=(12,8))
occupation_type_count=df_app["OCCUPATION_TYPE"].value_counts()
sns.barplot(x=occupation_type_count,y=occupation_type_count.index,palette="viridis")
plt.title("OCCUPATION_TYPE BAR_PLOT")
plt.xlabel("FREQUENCY")
plt.ylabel("OCCUPATION_TYPE")

for index,value in enumerate(occupation_type_count):
    plt.text(value,index,f'{value}',ha="left",va="center",color="black",fontsize=10,weight="normal")
plt.show()

In [ ]:
df_app["CNT_FAM_MEMBERS"].isnull().sum()

In [ ]:
df_app["CNT_FAM_MEMBERS"].describe()

In [ ]:
df_app["CNT_FAM_MEMBERS"]=df_app["CNT_FAM_MEMBERS"].fillna(df_app["CNT_FAM_MEMBERS"].median())

In [ ]:
df_app["CNT_FAM_MEMBERS"].isnull().sum()

In [ ]:
df_app["CNT_FAM_MEMBERS"].value_counts()

In [ ]:
df_app["NAME_TYPE_SUITE"]=df_app["NAME_TYPE_SUITE"].fillna(df_app["NAME_TYPE_SUITE"].mode()[0])

In [ ]:
df_app["NAME_TYPE_SUITE"].isnull().sum()

In [ ]:
plt.figure(figsize=(12,8))
name_type_count=df_app["NAME_TYPE_SUITE"].value_counts()
sns.barplot(x=name_type_count,y=name_type_count.index,palette="viridis")
plt.title("name_type_count")
plt.xlabel("frequency")
plt.ylabel("NAME_TYPE_SUITE")

for index,value in enumerate(name_type_count):
    plt.text(value,index,f'{value}',ha="left",va="center",color="black",fontsize=10)
plt.show()

In [ ]:
plt.figure(figsize=(10,8))
sns.countplot(y="NAME_TYPE_SUITE",data=df_app,color="purple")
plt.show()

In [ ]:
df_app.describe().columns

In [ ]:
amt_req=['AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR']

In [ ]:
df_app[amt_req].isnull().sum()

In [ ]:
df_app[amt_req].describe()

In [ ]:
plt.figure(figsize=(16,10))
sns.boxplot(df_app[amt_req],color="blue")
plt.xticks(rotation=45)
plt.show()

In [ ]:
df_app[amt_req]=df_app[amt_req].fillna(df_app[amt_req].median())

In [ ]:
df_app[amt_req].isnull().sum()

In [181]:
df_app.describe().columns.to_list()

['SK_ID_CURR',
 'TARGET',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'TOTALAREA_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [182]:
df_app[['DAYS_BIRTH','DAYS_EMPLOYED','DAYS_REGISTRATION','DAYS_ID_PUBLISH','DAYS_LAST_PHONE_CHANGE']]

,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,DAYS_LAST_PHONE_CHANGE
0,-9461,-637,-3648,-2120,-1134.0
1,-16765,-1188,-1186,-291,-828.0
2,-19046,-225,-4260,-2531,-815.0
3,-19005,-3039,-9833,-2437,-617.0
4,-19932,-3038,-4311,-3458,-1106.0
...,...,...,...,...,...
49994,-10667,-285,-2521,-3333,-14.0
49995,-20211,-4651,-11281,-3722,-1930.0
49996,-10280,-1158,-8620,-2604,-712.0
49997,-23485,-2181,-2662,-4200,-1989.0
49998,-19251,365243,-12934,-2783,-295.0

In [183]:
df_app[['DAYS_BIRTH','DAYS_EMPLOYED','DAYS_REGISTRATION','DAYS_ID_PUBLISH','DAYS_LAST_PHONE_CHANGE']]=abs(df_app[['DAYS_BIRTH','DAYS_EMPLOYED','DAYS_REGISTRATION','DAYS_ID_PUBLISH','DAYS_LAST_PHONE_CHANGE']])

In [184]:
df_app[['DAYS_BIRTH','DAYS_EMPLOYED','DAYS_REGISTRATION','DAYS_ID_PUBLISH','DAYS_LAST_PHONE_CHANGE']]

,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,DAYS_LAST_PHONE_CHANGE
0,9461,637,3648,2120,1134.0
1,16765,1188,1186,291,828.0
2,19046,225,4260,2531,815.0
3,19005,3039,9833,2437,617.0
4,19932,3038,4311,3458,1106.0
...,...,...,...,...,...
49994,10667,285,2521,3333,14.0
49995,20211,4651,11281,3722,1930.0
49996,10280,1158,8620,2604,712.0
49997,23485,2181,2662,4200,1989.0
49998,19251,365243,12934,2783,295.0