In [ ]:
# Pandas :- Pandas is a python package or a library which is used for handling large dataset,exploring
# data , manipulating data ,cleaning data ,transforming data and modeling data.
# their are 2 types of data structure:-
# 1 Series :- single dimension data structure for storing different datatype.
# 2 Data frame :- it is 2 dimensional structure look like a table ,store data in row and column

In [1]:
import pandas as pd

In [2]:
l=[10,20,30,40,50]
s=pd.Series(l)
print(s)
print(type(s))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
s=pd.Series([10,20,30,40,50],index=["a","s","d","e","f"],dtype="float64",name="python")
print(s)
print(s["d"])

a    10.0
s    20.0
d    30.0
e    40.0
f    50.0
Name: python, dtype: float64
30.0

In [5]:
s=pd.Series({"name":["abc","def","pqr"],"subject":["da","ds","de"],"fees":[100,200,300]})
print(s)

name       [abc, def, pqr]
subject       [da, ds, de]
fees       [100, 200, 300]
dtype: object

In [6]:
s=pd.Series(12)
print(s)

0    12
dtype: int64

In [7]:
s=pd.Series(12,index=[1,2,3,4,5,6,7])
print(s)

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64

In [9]:
s1=pd.Series(12,index=[1,2,3,4,5,6,7])
s2=pd.Series(12,index=[1,2,3,4,5])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5    24.0
6     NaN
7     NaN
dtype: float64

In [10]:
# DataFrame
l=[10,20,30,40,50]
df=pd.DataFrame(l)
df

    0
0  10
1  20
2  30
3  40
4  50

In [11]:
df=pd.DataFrame({"name":["abc","def","pqr"],"subject":["da","ds","de"],"fees":[100,200,300]})
df

  name subject  fees
0  abc      da   100
1  def      ds   200
2  pqr      de   300

In [12]:
d={"name":["abc","def","pqr"],"subject":["da","ds","de"],"fees":[100,200,300]}
df=pd.DataFrame(d,columns=["name","fees"],index=["a","s","d"])
df

  name  fees
a  abc   100
s  def   200
d  pqr   300

In [13]:
df=pd.DataFrame([[1,2,3,4,5],[10,20,30,40,50]])
df

    0   1   2   3   4
0   1   2   3   4   5
1  10  20  30  40  50

In [14]:
df=pd.DataFrame({"A":pd.Series([1,2,3,4]),"B":pd.Series([10,20,30,40]),1:pd.Series([100,200,300,400])})
df

   A   B    1
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400

In [15]:
df["C"]=df["A"]+df["B"]
df

   A   B    1   C
0  1  10  100  11
1  2  20  200  22
2  3  30  300  33
3  4  40  400  44

In [16]:
df["D"]=df["C"]>20
df

   A   B    1   C      D
0  1  10  100  11  False
1  2  20  200  22   True
2  3  30  300  33   True
3  4  40  400  44   True

In [17]:
df.insert(3,"python",df["A"])
df

   A   B    1  python   C      D
0  1  10  100       1  11  False
1  2  20  200       2  22   True
2  3  30  300       3  33   True
3  4  40  400       4  44   True

In [18]:
df.insert(3,"python_1",["abc","def","xyz","pqr"])
df

   A   B    1 python_1  python   C      D
0  1  10  100      abc       1  11  False
1  2  20  200      def       2  22   True
2  3  30  300      xyz       3  33   True
3  4  40  400      pqr       4  44   True

In [19]:
# delete
df.pop("python_1")
df

   A   B    1  python   C      D
0  1  10  100       1  11  False
1  2  20  200       2  22   True
2  3  30  300       3  33   True
3  4  40  400       4  44   True

In [20]:
del df[1]
df

   A   B  python   C      D
0  1  10       1  11  False
1  2  20       2  22   True
2  3  30       3  33   True
3  4  40       4  44   True