In [1]:
# set - collections of elements
# denoted by {} with csv.
# store only unique value
# unordered,unindexed,mutable and heterogenous in nature.
s=set()   # empty set
print(s)
print(type(s))

set()
<class 'set'>

In [2]:
s={10,20,30,40,10,20,10,"hello",10,20,10.5}
print(s)
print(type(s))
s.add(1000)   # mutable
print(s)

{10.5, 20, 40, 'hello', 10, 30}
<class 'set'>
{10.5, 20, 1000, 40, 'hello', 10, 30}

In [3]:
# iteration
s={10,20,30,40,10,20,10,"hello",10,20,10.5}
for i in s:
    print(i)

10.5
20
40
hello
10
30

In [4]:
# len()
s={10,20,30,40,"hello",10.5}
print(len(s))
count=0
for i in s:
    count=count+1
print(count)

6
6

In [5]:
s={100,1,10.5,20,99,-10,91}
print(max(s))
print(min(s))

100
-10

In [6]:
# add element to an existing set
s={10,20,10,30,40,"hello",10.5,11}
print(s)
s.add(1000)
print(s)

{10, 20, 40, 'hello', 10.5, 11, 30}
{10, 20, 1000, 40, 'hello', 10.5, 11, 30}

In [7]:
# pop()
s={10,20,30,40,"hello",10.5,100}
print(s.pop())
print(s)

10.5
{100, 20, 40, 'hello', 10, 30}

In [8]:
# remove()
s={10,20,30,40,"hello",10.5}
print(s)
s.remove(30)
print(s)
s.remove(1000)
print(s)

{10.5, 20, 40, 'hello', 10, 30}
{10.5, 20, 40, 'hello', 10}

KeyError: 1000

In [9]:
# discard()
s={10,20,30,40,"hello",10.5}
print(s)
s.discard(30)
print(s)
s.discard(1000)
print(s)

{10.5, 20, 40, 'hello', 10, 30}
{10.5, 20, 40, 'hello', 10}
{10.5, 20, 40, 'hello', 10}

In [10]:
s1={100,20,200,30,50}
s2={200,40,60,50,400,20}
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s1.symmetric_difference(s2))

{100, 200, 40, 400, 50, 20, 60, 30}
{200, 50, 20}
{100, 30}
{400, 100, 40, 60, 30}

In [11]:
s1={100,20,200,30,50}
s2={200,40,60,50,400,20}
print(s1|s2)
print(s1&s2)
print(s1-s2)
print(s1^s2)

{100, 200, 40, 400, 50, 20, 60, 30}
{200, 50, 20}
{100, 30}
{400, 100, 40, 60, 30}

In [12]:
import pandas as pd

In [13]:
df1=pd.DataFrame({"A":["abc","def","ert"],"B":[1,2,3],"C":["sd","er","tg"]})
df2=pd.DataFrame({"A":["abc","def","dfg"],"F":[1,2,3],"G":["sd","er","tg"]})

In [14]:
df1

     A  B   C
0  abc  1  sd
1  def  2  er
2  ert  3  tg

In [15]:
df2

     A  F   G
0  abc  1  sd
1  def  2  er
2  dfg  3  tg

In [16]:
set(df1.columns)&set(df2.columns)

{'A'}

In [17]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [18]:
df1.describe().columns

Index(['B'], dtype='object')

In [19]:
set(df1.columns)-set(df1.describe().columns)

{'A', 'C'}

In [20]:
!git add .

warning: in the working copy of 'python-basics/.ipynb_checkpoints/practise-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'python-basics/practise.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'python-basics/.ipynb_checkpoints/set-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'python-basics/set.ipynb', LF will be replaced by CRLF the next time Git touches it

In [21]:
!git commit -m "learned set"

[main 28e5595] learned set
 4 files changed, 1428 insertions(+), 2 deletions(-)
 create mode 100644 python-basics/.ipynb_checkpoints/set-checkpoint.ipynb
 create mode 100644 python-basics/set.ipynb

In [23]:
!git push

To https://github.com/rosesolanki29/daily-python-data-lab.git
   c02a726..28e5595  main -> main

In [1]:
# add element to an existing set
s={10,20,10,30,40,"hello",10.5,11}
print(s)
s.add(1000)
print(s)

{'hello', 10.5, 20, 40, 10, 11, 30}
{'hello', 10.5, 20, 40, 1000, 10, 11, 30}

In [1]:
# discard()
s={10,20,30,40,"hello",10.5}
print(s)
s.discard(30)
print(s)
s.discard(1000)
print(s)

{10.5, 20, 'hello', 40, 10, 30}
{10.5, 20, 'hello', 40, 10}
{10.5, 20, 'hello', 40, 10}

In [1]:
# remove()
s={10,20,30,40,"hello",10.5}
print(s)
s.remove(30)
print(s)
s.remove(1000)
print(s)

{10.5, 'hello', 20, 40, 10, 30}
{10.5, 'hello', 20, 40, 10}

KeyError: 1000

In [2]:
# frozenset() -collection of unique elements
# denoted by - constructor --- frozenset()
# unordered,unindexed and immutable and heterogenous
f=frozenset({10,20,10,30,40,"hello",10.5,10,10,20})
print(f)
print(type(f))

frozenset({10.5, 20, 40, 10, 'hello', 30})
<class 'frozenset'>

In [4]:
f=frozenset()
print(f)
print(type(f))

frozenset()
<class 'frozenset'>

In [9]:
l=[10,20,30,10,30,20,10,"hello",10.5]
t=(10,20,30,10,20,10,10,"hello",10.5)
s={10,20,30,10,300,10,"hello",10.5,10}
s1="welcome to bhopal"
print(frozenset(l))
print(frozenset(t))
print(frozenset(s))
print(frozenset(s1))

frozenset({10, 10.5, 20, 'hello', 30})
frozenset({10, 10.5, 20, 'hello', 30})
frozenset({10.5, 20, 10, 300, 'hello', 30})
frozenset({'o', 'b', 'p', 'm', 't', 'c', 'h', 'w', 'a', ' ', 'e', 'l'})

In [10]:
!git add .

warning: in the working copy of 'python-basics/set.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'python-basics/.ipynb_checkpoints/functions-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'python-basics/functions.ipynb', LF will be replaced by CRLF the next time Git touches it

In [11]:
!git commit -m "learned frozenset"

[main f6e5e30] learned frozenset
 3 files changed, 1000 insertions(+), 66 deletions(-)
 create mode 100644 python-basics/.ipynb_checkpoints/functions-checkpoint.ipynb
 create mode 100644 python-basics/functions.ipynb

In [12]:
!git push

To https://github.com/rosesolanki29/daily-python-data-lab.git
   f6976dc..f6e5e30  main -> main